"""add soft delete fields

Revision ID: ddd3f0bc9866
Revises: 90d961b8d15c
Create Date: 2026-02-19 10:01:21.290740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd3f0bc9866'
down_revision: Union[str, Sequence[str], None] = '90d961b8d15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
